CREATE TABLE buyer (
	buyer_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	first_name VARCHAR(100) NOT NULL,
	last_name VARCHAR(100) NOT NULL,
	title VARCHAR(100)
);

CREATE TABLE buyer_address (
	buyer_address_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	city VARCHAR(100) NOT NULL,
	street VARCHAR(100) NOT NULL,
	home_number VARCHAR(100)
);

CREATE TABLE "order" (
	order_nr BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	buyer_id BIGINT NOT NULL,
	order_status VARCHAR(32) NOT NULL,
	order_time TIMESTAMP NOT NULL,
	payment_option VARCHAR(32) NOT NULL,
	delivery_address_id BIGINT NOT NULL,
	contact_number VARCHAR(100),
	note VARCHAR(500),
	currency VARCHAR(3) NOT NULL,
	total_price DECIMAL(12, 2) NOT NULL,
	CONSTRAINT fk_order_buyer FOREIGN KEY (buyer_id) REFERENCES buyer (buyer_id),
	CONSTRAINT fk_order_delivery_address FOREIGN KEY (delivery_address_id) REFERENCES buyer_address (buyer_address_id)
);

CREATE TABLE order_item (
	order_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	order_nr BIGINT NOT NULL,
	item_nr SMALLINT NOT NULL,
	name VARCHAR(100) NOT NULL,
	quantity SMALLINT NOT NULL,
	price DECIMAL(12, 2) NOT NULL,
	CONSTRAINT fk_order_item_order FOREIGN KEY (order_nr) REFERENCES "order" (order_nr),
	CONSTRAINT uc_order_item_number UNIQUE (order_nr, item_nr)
);
